package com.wormhole.browser.core.webview.blocking

object BlockList {

    val TRACKERS: Set<String> = setOf(

        "google-analytics.com",
        "googletagmanager.com",
        "googletagservices.com",
        "googlesyndication.com",
        "google-analytics.l.google.com",
        "app-measurement.com",
        "firebase-settings.crashlytics.com",
        "crashlytics.com",

        "connect.facebook.net",
        "an.facebook.com",

        "omtrdc.net",
        "2o7.net",
        "demdex.net",
        "everesttech.net",

        "segment.io",
        "segment.com",
        "mixpanel.com",
        "amplitude.com",
        "hotjar.com",
        "fullstory.com",
        "mouseflow.com",
        "clicktale.net",
        "quantserve.com",
        "quantcount.com",
        "scorecardresearch.com",
        "comscore.com",
        "chartbeat.com",
        "chartbeat.net",
        "newrelic.com",
        "nr-data.net",
        "bugsnag.com",
        "sentry.io",
        "branch.io",
        "appsflyer.com",
        "adjust.com",
        "kochava.com",
        "mparticle.com",
        "heap.io",
        "heapanalytics.com",
        "logrocket.com",
        "clarity.ms",
        "bat.bing.com",
        "mc.yandex.ru",
        "matomo.cloud",
        "piwik.pro",
        "cloudflareinsights.com",
        "hs-analytics.net",
        "hsadspixel.net",
        "usemessages.com",

        "iesnare.com",
        "threatmetrix.com",
        "maxmind.com",
    )

    val ADS: Set<String> = setOf(

        "doubleclick.net",
        "adservice.google.com",
        "googleadservices.com",
        "googlesyndication.com",
        "pagead2.googlesyndication.com",
        "adsystem.google.com",
        "admob.com",

        "adnxs.com",
        "rubiconproject.com",
        "openx.net",
        "pubmatic.com",
        "criteo.com",
        "criteo.net",
        "taboola.com",
        "outbrain.com",
        "mgid.com",
        "revcontent.com",
        "adroll.com",
        "advertising.com",
        "adform.net",
        "smartadserver.com",
        "yieldmo.com",
        "sharethrough.com",
        "media.net",
        "casalemedia.com",
        "indexexchange.com",
        "contextweb.com",
        "spotxchange.com",
        "spotx.tv",
        "amazon-adsystem.com",
        "moatads.com",
        "adtechus.com",
        "adtech.de",
        "bidswitch.net",
        "33across.com",
        "adroll.com",
        "adcolony.com",
        "applovin.com",
        "unityads.unity3d.com",
        "vungle.com",
        "chartboost.com",
        "inmobi.com",
        "mopub.com",
        "flashtalking.com",
        "gemini.yahoo.com",
        "adtechjp.com",
        "adsafeprotected.com",
        "serving-sys.com",
        "turn.com",
        "tapad.com",
        "exponential.com",
        "adblade.com",
        "propellerads.com",
        "popads.net",
        "popcash.net",
        "exoclick.com",
        "juicyads.com",
        "trafficjunky.net",
        "zedo.com",
        "bidvertiser.com",
        "adcash.com",
    )

    val POPUP_AD_NETWORKS: Set<String> = setOf(
        "popads.net",
        "popcash.net",
        "propellerads.com",
        "adcash.com",
        "exoclick.com",
        "trafficjunky.net",
        "juicyads.com",
        "clickadu.com",
        "onclickmax.com",
        "adsterra.com",
        "hilltopads.net",
    )
}
